### ISSUE TITLE
Plugin doesn't take any action unless data.yaml has at least one chunk in it

### ISSUE THREAD

**Issue by hiinaspace** [Huskehhh/HoneyPopulator#11]
`isLoadingData` is only set to false if chunk list is non-empty: 

https://github.com/Huskehhh/HoneyPopulator/blob/cb9713130d538ef8c38a15ef245c533d097e7fdc/src/main/java/pro/husk/honeypopulator/HoneyPopulator.java#L298-L300

and the onchunk event checks for that bool:

https://github.com/Huskehhh/HoneyPopulator/blob/cb9713130d538ef8c38a15ef245c533d097e7fdc/src/main/java/pro/husk/honeypopulator/HoneyPopulator.java#L118-L120

I had to create a dummy `"world,0,0"` entry in data.yml to get the plugin to start checking for generation.

**Comment by Huskehhh** [comment]
Heyo. Cheers for the issue!

I'm not even sure why I bothered adding an empty check on this, will push through change shortly 👍
