### ISSUE TITLE
Non-Standard Tree/EWG support

### ISSUE THREAD

**Issue by budgidiere** [Huskehhh/HoneyPopulator#13]
Is it possible to add a toggle to place a beehive on non-standard trees?

**Comment by Huskehhh** [comment]
What do you mean by non-standard trees? Those made by players? Or outside the scope of regular generation ie: extreme hills biome etc

**Comment by budgidiere** [comment]
![image](https://user-images.githubusercontent.com/25417900/80285801-fb047a80-86ec-11ea-958f-d8f667041137.png)
Trees like this which are generated naturally by EWG. Basically just asking for a toggle that places it next to any logs.

**Comment by Huskehhh** [comment]
Sorry, I'm not so well versed in EWG. Are these trees in the correct biome for bee nest generation? Or do you want this toggle to ignore biome checks too?

**Comment by budgidiere** [comment]
these are just random trees to show they are not normal. But unless it's a vanilla tree bee hives do not spawn. I tried boosting chance to 100 for everything and the only trees that got bees was vanilla trees.

**Comment by Huskehhh** [comment]
Yeah I understand that but do you want biome checks to be ignored or honoured with this proposed toggle?

**Comment by budgidiere** [comment]
@Huskehhh I would like biome checks to not be ignored :) EWG classifies it's biomes properly. Also thank you for fix!
