### ISSUE TITLE
Enhancement Request. Type of tree and more biomes.

### ISSUE THREAD

**Issue by DiegoDaniel** [Huskehhh/HoneyPopulator#16]
![image](https://user-images.githubusercontent.com/14002872/80554126-7e022b00-89a2-11ea-84f4-1b7befb431ab.png)
Epic World Generator is the best custom world creator, with more than 30 custom biomes. 

The problem is that the trees are not vanilla, So Bee Nests are not generating properly, even with:

generation-chance-plains: 75.0
generation-chance-flower_forest: 72.0

If you can see in the picture, generated trees are with that type of wood, not the regular one.

And Epic World Generator have too many "forest" where it would be great to have bees too!

Is there any chance to make bees appear on selected biomes? Like:

generation-chance-forest: <configurablevalue>
generation-chance-jungle-hills: -1 // 0

**Comment by Huskehhh** [comment]
Hey! have you enabled

``ignore-vanilla-tree-checks`` in the config?

As for the wood + biome checks, I guess I can further implement support for custom world generation 👍

**Comment by DiegoDaniel** [comment]
Yes, it's activated but bees and % only working on acacia. 

(i've set 75%) 
https://media.discordapp.net/attachments/645359168256999443/704874497244790854/unknown.png?width=729&height=410

**Comment by Huskehhh** [comment]
Yeah I'll have to ponder this one :P
I don't have a copy of EpicWordGenerator so further supporting it is going to be difficult. Maybe it's better to create a request to the developer that bee nests are generated with the world

**Comment by DiegoDaniel** [comment]
Fixed on EWG New versions.
