### ISSUE TITLE
generated bee nests face towards log or get locked

### ISSUE THREAD

**Issue by JustEli** [Huskehhh/HoneyPopulator#4]
Some bee nests get locked inbetween blocks, which makes bees not able to enter or leave the nest.
![image](https://user-images.githubusercontent.com/8517465/71422818-2ca8fe80-2685-11ea-8f62-d1198b20b3b6.png)

And bee nests always face the same direction, so it has a chance to spawn with its face towards a log like here, which, again, makes bees not able to enter or leave the nest.
![image](https://user-images.githubusercontent.com/8517465/71422852-5bbf7000-2685-11ea-958e-3e0214930990.png)

**Comment by Huskehhh** [comment]
Ah awesome, thanks heaps for the report.

I’ll look into it :)

**Comment by snurre0** [comment]
They always seem to generating facing north, if you haven't figured that out yet (which I bet you have :p )

**Comment by Huskehhh** [comment]
Yessir! I'm currently on holidays but when I get back I'll fix this asap :)

**Comment by JustEli** [comment]
this still seems to bee an issue
