### ISSUE TITLE
Enable HoneyPopulator on startup

### ISSUE THREAD

**Issue by snurre0** [Huskehhh/HoneyPopulator#5]
Hi.

This plugin is really nice, exactly what I need. There is only one thing I'm missing for it to be perfect.
It doesn't seem to be a way to enable the bee hive populating by default at startup. It that something that can be added?
Having a server with scheduled restarts every day, makes this not too easy to use.
We want our players to be able to expore and find hives without us having to run a command after every restart. Would be awesome if something like that could be added! :)

**Comment by Huskehhh** [comment]
Nice idea. Done. :)
