### ISSUE TITLE
empty bee nests 

### ISSUE THREAD

**Issue by thedourn** [Huskehhh/HoneyPopulator#7]
Hello
thank you for your plugin which saves me my server!
But I have a little problem the bee nests appear empty no bees are inside.
Thank you
Thedourn

**Comment by Huskehhh** [comment]
Hey man. A random number of bees between 1-3 will spawn near the bee nest, they may get stuck in blocks and die though, resulting in the nest being uninhabited.

**Comment by thedourn** [comment]
I searched on a tenth of a generated nest and 0 bees

**Comment by Huskehhh** [comment]
Didn't mean to close issue! Oops!

I've pushed a change that potentially fixes this issue.

Available from: https://ci.husk.pro/job/HoneyPopulator/22/

**Comment by thedourn** [comment]
no bee but if i go on chunks not generated the spawn bee

**Comment by thedourn** [comment]
I mean no generate in 1.14

**Comment by Huskehhh** [comment]
Bees don't exist in 1.14, so they wont be able to generate

**Comment by thedourn** [comment]
I know but I put your car plugin I pass my server in 1.15 and on the old part generated in 1.14 the spawn hives thanks to your plugin but the hives are empty and in the discovery of the server in the part not generated in 1.14 the bees spawn.

I do of course my tests with your plugin in 1.15

**Comment by Huskehhh** [comment]
I see. If you wish for the bees to spawn in the 1.14 generated chunks, delete the data.yml (this will force the plugin to re-process every chunk)

This plugin however will not run in chunks that are generated by 1.15, as it would result in doubling up on bees!

**Comment by thedourn** [comment]
ok then I think I understood the problem because I pass the card in the "Optimize World" tools of the minecraft launcher.
So maybe the plugin is blocking the bee spawn because it believes that the chunk has just been generated.
I will test

**Comment by Huskehhh** [comment]
Ahh I see. if that's the case I can provide you a custom jar that will work regardless

**Comment by thedourn** [comment]
still no bee

**Comment by Huskehhh** [comment]
Try this: https://husk.pro/dl/HoneyPopulator-1.1-SNAPSHOT-ALL_CHUNKS.jar

**Comment by thedourn** [comment]
it still does not work and when I break a nest I have an error in the console:
[12:06:48 ERROR]: POI data mismatch: never registered at BlockPosition{x=-15627, y=64, z=650}

**Comment by Huskehhh** [comment]
I'm really not sure mate, I cannot replicate this in any way shape or form

**Comment by thedourn** [comment]
which version of paper do you use? but i'm on build 50

**Comment by Huskehhh** [comment]
Also on the latest build

**Comment by thedourn** [comment]
do you need another plugin to make it work?

**Comment by thedourn** [comment]
ok
thank

**Comment by thedourn** [comment]
I just looked for when the doc of spigot-api that it might be necessary in addition to spawn the bee to define him the nest with the setHive
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Bee.html

**Comment by Huskehhh** [comment]
Correct :/

The weird issue as of current is that the code doesn't progress past this line
https://github.com/Huskehhh/HoneyPopulator/blob/master/src/main/java/pro/husk/honeypopulator/HoneyPopulator.java#L113

Hence it wont spawn the bees or rotate away from north

**Comment by Huskehhh** [comment]
fixed with build 27
